### PR TITLE
Add support for TSX/TMX files

### PR DESCRIPTION
**Pull request by winniehell**

### CODE REVIEW

**Comment by winniehell** [comment]
I haven't tested these changes yet (still need to find out how :smiley: ).

**Comment by englercj** [comment]
Closing this for now. XML support is likely a big feature since even if the loader could load it the core library wouldn't be able to take it as a parameter without major changes.

**Comment by winniehell** [comment]
Makes sense! :+1: 

I have switched to JSON maps with inlined tilesets (no TSX) for my projects meanwhile.

**Comment by englercj** [comment]
Turns out that the XML format is actually deprecated in recent versions of Tiled so it is unlikely I'll ever add support for it here.

**Pull request closed without merging**
